- alias: Notify of Frigate Events
  trigger:
  - platform: mqtt
    topic: frigate/events
  action:
  - service: notify.mobile_app_drews_iphone
    data_template:
      message: A {{trigger.payload_json["after"]["label"]}} was detected.
      data:
        image: https://o61sm9rwgmfhut7k9el3fkn74hmq99pd.ui.nabu.casa/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android
        tag: '{{trigger.payload_json["after"]["id"]}}'
  id: 5a0bbec096044b6e8deb30f6f597bca5
- id: '1634740684725'
  alias: Frigate Notification
  description: ''
  use_blueprint:
    path: hunterjm/frigate_notification.yaml
    input:
      camera: courtyard-south
      notify_device: 7516b6f48fd25b5189d0c1d5e55e4556
