# - id: '1609167933911'
#   alias: HA config push to Git
#   description: ''
#   trigger:
#   - platform: time
#     at: '23:00'
#   condition: []
#   action:
#   - service: hassio.addon_stdin
#     data:
#       addon: a0d7b954_ssh
#       input: /config/ha_gitpush.sh
#   mode: single

- alias: Notify of Frigate Events
  trigger:
  - platform: mqtt
    topic: frigate/events
  action:
  - service: notify.mobile_app_andrews_iphone_12_pro
    data_template:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: !secret frigate_notification_url
        tag: '{{trigger.payload_json["after"]["id"]}}'